# Generated by Django 3.2.9 on 2021-11-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
