# Generated by Django 3.2.9 on 2021-11-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0002_room_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='projector',
            field=models.BooleanField(default=False),
        ),
    ]
