# Generated by Django 3.2.9 on 2021-11-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0003_room_projector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=250)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_app.room')),
            ],
            options={
                'unique_together': {('date', 'id')},
            },
        ),
    ]
