# Generated by Django 3.2.9 on 2021-11-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0005_rename_room_id_reserve_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
