# Generated by Django 3.2.9 on 2021-11-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0006_alter_room_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserve',
            new_name='Reservation',
        ),
    ]
