# Generated by Django 3.2.9 on 2021-11-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0007_rename_reserve_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='availability',
        ),
    ]
